export { Home } from './home/Home'
export { SinglePost } from './singlePost/SinglePost'
export { ProfilePage } from './profile/ProfilePage'
export { Login } from './auth/Login'
export { Signup } from './auth/Signup'
export { Explore } from './explore/Explore'
export { BookmarkPage } from './bookmark/BookmarkPage'
export { LikedPage } from './liked/LikedPage'
