export { NavHeader } from './nav/NavHeader'
export { NavLeft } from './nav/NavLeft'
export { NewPost } from './newPost/NewPost'
export { Search } from './search/Search'
export { Account } from './account/Account'
export { FollowOther } from './home/FollowOther'
export { HomePosts } from './home/HomePosts'
export { HomePost } from './home/HomePost'
export { Profile } from './profile/Profile'
export { Bookmark } from './bookmark/Bookmark'
export { Like } from './like/Like'
export { SinglePost } from './singlePost/SinglePost'
export { ExplorePosts } from './explore/ExplorePosts'
export { EditPostModal } from './modal/EditPostModal'
export { User } from './profile/User'
// export { Like } from './singlePost/ComentVote'
