export { NavHeader } from './nav/NavHeader'
export { NavLeft } from './nav/NavLeft'
export { NewPost } from './newPost/NewPost'
export { Search } from './search/Search'
export { Account } from './account/Account'
export { FollowOther } from './home/FollowOther'
export { HomePosts } from './home/HomePosts'
export { Profile } from './profile/Profile'
export { ProfilePost } from './profile/ProfilePost'
export { Bookmark } from './bookmark/Bookmark'
export { Like } from './like/Like'
export { SinglePost } from './singlePost/SinglePost'
export { Explore } from './explore/Explore'
// export { Like } from './singlePost/ComentVote'
